on:
  workflow_dispatch: ~
  push:
    branches:
      - "libcurl-julia-bin"

jobs:
  makepkg:
    container: archlinux:base-devel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          path: libcurl-julia-bin
          ref: libcurl-julia-bin
      - run: pacman-key --init
      - run: pacman -Syu --noconfirm dbus-daemon-units
      - run: |-
          makepkg -V
          echo 'PACKAGER="Heptazhou <zhou@0h7z.com>"' >> /etc/makepkg.conf
          sed -re 's/\b(EUID) == 0\b/\1 < -0/g' -i /bin/makepkg
      - run: |-
          cd libcurl-julia-bin
          makepkg -si --noconfirm
          mv -vt .. *.pkg.tar.zst
      - run: ls -lav *.pkg.tar.zst
      - uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          path: "*.pkg.tar.zst"
