on:
  workflow_dispatch: ~

jobs:
  make:
    container: archlinux:base-devel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          path: mingw-w64-zlib
          ref: mingw-w64-zlib
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          path: nsis
          ref: nsis
      - run: "pacman-key --init"
      - run: "pacman -Syu --noconfirm"
      - run: |-
          makepkg -V
          sed -ri 's/(EUID) == 0/\1 < 0/g' /bin/makepkg
          cd mingw-w64-zlib
          makepkg -si --noconfirm
          mv -vt .. *.pkg.tar.zst
          cd ..
          cd nsis
          makepkg -si --noconfirm
          mv -vt .. *.pkg.tar.zst
          cd ..
      - uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          path: "*.pkg.tar.zst"
