on:
  workflow_dispatch: ~
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/repo-sync.yml"
  schedule:
    - cron: "0 */4 * * *"

jobs:
  _7-zip-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: heptazhou/github-sync@v2.3.0
        with:
          source_repo: https://aur.archlinux.org/7-zip-full.git
          source_branch: master
          destination_branch: 7-zip-full
          github_token: ${{ secrets.PAT }}
  apt-zsh-completion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: heptazhou/github-sync@v2.3.0
        with:
          source_repo: https://aur.archlinux.org/apt-zsh-completion.git
          source_branch: master
          destination_branch: apt-zsh-completion
          github_token: ${{ secrets.PAT }}
  conda-zsh-completion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: heptazhou/github-sync@v2.3.0
        with:
          source_repo: https://aur.archlinux.org/conda-zsh-completion.git
          source_branch: master
          destination_branch: conda-zsh-completion
          github_token: ${{ secrets.PAT }}
  glibc-linux4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: heptazhou/github-sync@v2.3.0
        with:
          source_repo: https://aur.archlinux.org/glibc-linux4.git
          source_branch: master
          destination_branch: glibc-linux4
          github_token: ${{ secrets.PAT }}
  iraf-bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: heptazhou/github-sync@v2.3.0
        with:
          source_repo: https://aur.archlinux.org/iraf-bin.git
          source_branch: master
          destination_branch: iraf-bin
          github_token: ${{ secrets.PAT }}
  libcurl-julia-bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: heptazhou/github-sync@v2.3.0
        with:
          source_repo: https://aur.archlinux.org/libcurl-julia-bin.git
          source_branch: master
          destination_branch: libcurl-julia-bin
          github_token: ${{ secrets.PAT }}
  locale-mul_zz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: heptazhou/github-sync@v2.3.0
        with:
          source_repo: https://aur.archlinux.org/locale-mul_zz.git
          source_branch: master
          destination_branch: locale-mul_zz
          github_token: ${{ secrets.PAT }}
  mingw-w64-zlib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: heptazhou/github-sync@v2.3.0
        with:
          source_repo: https://aur.archlinux.org/mingw-w64-zlib.git
          source_branch: master
          destination_branch: mingw-w64-zlib
          github_token: ${{ secrets.PAT }}
  nsis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: heptazhou/github-sync@v2.3.0
        with:
          source_repo: https://aur.archlinux.org/nsis.git
          source_branch: master
          destination_branch: nsis
          github_token: ${{ secrets.PAT }}
  python312:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: heptazhou/github-sync@v2.3.0
        with:
          source_repo: https://aur.archlinux.org/python312.git
          source_branch: master
          destination_branch: python312
          github_token: ${{ secrets.PAT }}
  wine-wow64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: heptazhou/github-sync@v2.3.0
        with:
          source_repo: https://aur.archlinux.org/wine-wow64.git
          source_branch: master
          destination_branch: wine-wow64
          github_token: ${{ secrets.PAT }}
  xgterm-bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: heptazhou/github-sync@v2.3.0
        with:
          source_repo: https://aur.archlinux.org/xgterm-bin.git
          source_branch: master
          destination_branch: xgterm-bin
          github_token: ${{ secrets.PAT }}
  yay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: heptazhou/github-sync@v2.3.0
        with:
          source_repo: https://aur.archlinux.org/yay.git
          source_branch: master
          destination_branch: yay
          github_token: ${{ secrets.PAT }}
