on:
  workflow_dispatch: ~
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/repo-sync.yml"
  schedule:
    - cron: "0 */4 * * *"

jobs:
  apt-zsh-completion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          token: ${{ secrets.PAT }}
      - run: |-
          git version
          git config --global color.ui always
          git config --global log.date iso
          git config --global log.decorate short
          git remote -v
          git remote add  upstream https://github.com/archlinux/aur.git -t apt-zsh-completion -f
          git push origin upstream/apt-zsh-completion:apt-zsh-completion -f
  conda-zsh-completion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          token: ${{ secrets.PAT }}
      - run: |-
          git version
          git config --global color.ui always
          git config --global log.date iso
          git config --global log.decorate short
          git remote -v
          git remote add  upstream https://github.com/archlinux/aur.git -t conda-zsh-completion -f
          git push origin upstream/conda-zsh-completion:conda-zsh-completion -f
  iraf-bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          token: ${{ secrets.PAT }}
      - run: |-
          git version
          git config --global color.ui always
          git config --global log.date iso
          git config --global log.decorate short
          git remote -v
          git remote add  upstream https://github.com/archlinux/aur.git -t iraf-bin -f
          git push origin upstream/iraf-bin:iraf-bin -f
  libcurl-julia-bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          token: ${{ secrets.PAT }}
      - run: |-
          git version
          git config --global color.ui always
          git config --global log.date iso
          git config --global log.decorate short
          git remote -v
          git remote add  upstream https://github.com/archlinux/aur.git -t libcurl-julia-bin -f
          git push origin upstream/libcurl-julia-bin:libcurl-julia-bin -f
  locale-mul_zz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          token: ${{ secrets.PAT }}
      - run: |-
          git version
          git config --global color.ui always
          git config --global log.date iso
          git config --global log.decorate short
          git remote -v
          git remote add  upstream https://github.com/archlinux/aur.git -t locale-mul_zz -f
          git push origin upstream/locale-mul_zz:locale-mul_zz -f
  mingw-w64-zlib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          token: ${{ secrets.PAT }}
      - run: |-
          git version
          git config --global color.ui always
          git config --global log.date iso
          git config --global log.decorate short
          git remote -v
          git remote add  upstream https://github.com/archlinux/aur.git -t mingw-w64-zlib -f
          git push origin upstream/mingw-w64-zlib:mingw-w64-zlib -f
  nsis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          token: ${{ secrets.PAT }}
      - run: |-
          git version
          git config --global color.ui always
          git config --global log.date iso
          git config --global log.decorate short
          git remote -v
          git remote add  upstream https://github.com/archlinux/aur.git -t nsis -f
          git push origin upstream/nsis:nsis -f
  python310:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          token: ${{ secrets.PAT }}
      - run: |-
          git version
          git config --global color.ui always
          git config --global log.date iso
          git config --global log.decorate short
          git remote -v
          git remote add  upstream https://github.com/archlinux/aur.git -t python310 -f
          git push origin upstream/python310:python310 -f
  python311:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          token: ${{ secrets.PAT }}
      - run: |-
          git version
          git config --global color.ui always
          git config --global log.date iso
          git config --global log.decorate short
          git remote -v
          git remote add  upstream https://github.com/archlinux/aur.git -t python311 -f
          git push origin upstream/python311:python311 -f
  python312:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          token: ${{ secrets.PAT }}
      - run: |-
          git version
          git config --global color.ui always
          git config --global log.date iso
          git config --global log.decorate short
          git remote -v
          git remote add  upstream https://github.com/archlinux/aur.git -t python312 -f
          git push origin upstream/python312:python312 -f
  xgterm-bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          token: ${{ secrets.PAT }}
      - run: |-
          git version
          git config --global color.ui always
          git config --global log.date iso
          git config --global log.decorate short
          git remote -v
          git remote add  upstream https://github.com/archlinux/aur.git -t xgterm-bin -f
          git push origin upstream/xgterm-bin:xgterm-bin -f
  yay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          token: ${{ secrets.PAT }}
      - run: |-
          git version
          git config --global color.ui always
          git config --global log.date iso
          git config --global log.decorate short
          git remote -v
          git remote add  upstream https://github.com/archlinux/aur.git -t yay -f
          git push origin upstream/yay:yay -f
